#!/usr/bin/env node

import { execFile } from 'node:child_process';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { promisify } from 'node:util';
import { fileURLToPath } from 'node:url';

const execFileAsync = promisify(execFile);
const rootDir = dirname(fileURLToPath(import.meta.url));
const versionFile = join(rootDir, 'VERSION');
const versionModuleFile = join(rootDir, 'src', 'version.js');
const buildInfoFile = join(rootDir, 'dist', 'build-info.json');
const packageFile = join(rootDir, 'package.json');

function fail(message) {
  console.error(message);
  process.exitCode = 1;
}

async function readText(path) {
  return readFile(path, 'utf8');
}

async function readVersion() {
  const version = (await readText(versionFile)).trim();

  if (!version) {
    throw new Error('VERSION is empty.');
  }

  const semverish = /^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)?$/;

  if (!semverish.test(version)) {
    throw new Error(`VERSION must look like semver, for example 0.1.0-dev. Got: ${version}`);
  }

  return version;
}

async function readPackageName() {
  const packageJson = JSON.parse(await readText(packageFile));
  return packageJson.name || 'walk-bike-run';
}

async function writeVersionModule(version) {
  const contents = `// Generated by build.js from ../VERSION.\n// Do not edit this file directly.\n\nexport const APP_VERSION = ${JSON.stringify(version)};\n`;
  await writeFile(versionModuleFile, contents);
}

async function getGitValue(args) {
  try {
    const { stdout } = await execFileAsync('git', args, { cwd: rootDir });
    return stdout.trim();
  } catch {
    return null;
  }
}

async function getGitInfo() {
  const [commit, branch, status] = await Promise.all([
    getGitValue(['rev-parse', '--short', 'HEAD']),
    getGitValue(['branch', '--show-current']),
    getGitValue(['status', '--short']),
  ]);

  return {
    branch,
    commit,
    dirty: Boolean(status),
  };
}

async function writeBuildInfo({ name, version }) {
  await mkdir(dirname(buildInfoFile), { recursive: true });

  const buildInfo = {
    name,
    version,
    builtAt: new Date().toISOString(),
    git: await getGitInfo(),
  };

  await writeFile(buildInfoFile, `${JSON.stringify(buildInfo, null, 2)}\n`);
}

async function runViteBuild() {
  const { build } = await import('vite');
  await build();
}

async function main() {
  const args = new Set(process.argv.slice(2));
  const syncOnly = args.has('--sync-only');

  const [name, version] = await Promise.all([readPackageName(), readVersion()]);

  await writeVersionModule(version);

  if (syncOnly) {
    console.log(`Synced ${name} version ${version}`);
    return;
  }

  await runViteBuild();
  await writeBuildInfo({ name, version });

  console.log(`Built ${name} ${version}`);
}

main().catch((error) => {
  fail(error instanceof Error ? error.message : String(error));
});
