#!/usr/bin/env node

import { spawnSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const rootDir = dirname(fileURLToPath(import.meta.url));
const versionPath = join(rootDir, 'VERSION');
const srcVersionPath = join(rootDir, 'src', 'version.js');
const packagePath = join(rootDir, 'package.json');
const distDir = join(rootDir, 'dist');
const buildInfoPath = join(distDir, 'build-info.json');

function readVersion() {
  if (!existsSync(versionPath)) {
    throw new Error('Missing top-level VERSION file.');
  }

  const version = readFileSync(versionPath, 'utf8').trim();
  if (!version) {
    throw new Error('VERSION is empty.');
  }

  return version;
}

function writeIfChanged(path, content) {
  const current = existsSync(path) ? readFileSync(path, 'utf8') : null;
  if (current !== content) {
    writeFileSync(path, content);
  }
}

function syncVersionFile(version) {
  const content = `// Generated by build.js from ../VERSION. Do not edit by hand.\nexport const APP_VERSION = ${JSON.stringify(version)};\n`;
  writeIfChanged(srcVersionPath, content);
}

function checkPackageVersion(version) {
  if (!existsSync(packagePath)) return;

  const pkg = JSON.parse(readFileSync(packagePath, 'utf8'));
  if (pkg.version && pkg.version !== version) {
    console.warn(
      `Warning: package.json version (${pkg.version}) does not match VERSION (${version}).`,
    );
  }
}

function runViteBuild() {
  const npx = process.platform === 'win32' ? 'npx.cmd' : 'npx';
  const result = spawnSync(npx, ['vite', 'build'], {
    cwd: rootDir,
    stdio: 'inherit',
    shell: false,
  });

  if (result.error) {
    throw result.error;
  }

  if (result.status !== 0) {
    process.exit(result.status ?? 1);
  }
}

function writeBuildInfo(version) {
  mkdirSync(distDir, { recursive: true });
  const info = {
    app: 'Walk Bike Run',
    version,
    builtAt: new Date().toISOString(),
  };
  writeFileSync(buildInfoPath, `${JSON.stringify(info, null, 2)}\n`);
}

function main() {
  const version = readVersion();
  syncVersionFile(version);
  checkPackageVersion(version);

  if (process.argv.includes('--sync-version')) {
    console.log(`Synced src/version.js from VERSION: ${version}`);
    return;
  }

  runViteBuild();
  writeBuildInfo(version);
  console.log(`Built Walk Bike Run ${version}`);
}

main();
